services:
  db:
    image: ankane/pgvector:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - '5557:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
