name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Frontend Cache
      - name: Cache Frontend Dependencies
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package.json', 'frontend/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      # Frontend CI
      - name: Install frontend dependencies
        run: cd frontend && bun install

      - name: Frontend Lint
        run: cd frontend && bun run lint

      - name: Frontend Type check
        run: cd frontend && bun run tsc -b

      - name: Frontend Build
        run: cd frontend && bun run build

      # Backend Cache
      - name: Cache Backend Dependencies
        uses: actions/cache@v3
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-backend-${{ hashFiles('backend/package.json', 'backend/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-backend-

      # Backend CI
      - name: Install backend dependencies
        run: cd backend && bun install

      - name: Generate Prisma Client
        run: cd backend && bunx prisma generate

      - name: Check Drizzle Schema
        run: cd backend && bunx drizzle-kit check

      - name: Backend Lint
        run: cd backend && bun run lint

      - name: Backend Type check
        run: cd backend && bun run type-check

      - name: Backend Build
        run: cd backend && bun run build
