name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Frontend CI
      - name: Install frontend dependencies
        run: cd frontend && bun install

      - name: Frontend Lint
        run: cd frontend && bun run lint

      - name: Frontend Type check
        run: cd frontend && bun run tsc -b

      - name: Frontend Build
        run: cd frontend && bun run build

      # Backend CI
      - name: Install backend dependencies
        run: cd backend && bun install

      - name: Backend Lint
        run: cd backend && bun run lint

      - name: Backend Type check
        run: cd backend && bun run type-check

      - name: Backend Build
        run: cd backend && bun run build
