name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: cd frontend && bun install

      - name: Lint
        run: cd frontend && bun run lint

      - name: Type check
        run: cd frontend && bun run tsc -b

      - name: Build
        run: cd frontend && bun run build
